# Generated by Django 5.2.7 on 2025-10-11 04:46

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('major', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, default='')),
                ('avatar_url', models.URLField(blank=True, max_length=500, null=True)),
                ('learning_radius_km', models.FloatField(default=5.0)),
                ('geom_last_point', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='Last known geographic location of the user', null=True, srid=4326)),
                ('privacy_level', models.CharField(choices=[('open', 'Open'), ('friends_of_friends', 'Friends of Friends'), ('private', 'Private')], default='open', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('banned', 'Banned'), ('deleted', 'Deleted')], default='active', max_length=20)),
                ('last_active_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(blank=True, db_column='school_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='locations.school')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'indexes': [models.Index(fields=['email'], name='idx_users_email'), models.Index(fields=['last_active_at'], name='idx_users_last_active'), models.Index(fields=['school', 'year'], name='idx_users_school_year')],
            },
        ),
    ]
