# Generated by Django 5.2.7 on 2025-10-30 13:38

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('session_type', models.CharField(choices=[('in_person', 'In Person'), ('virtual', 'Virtual'), ('hybrid', 'Hybrid')], default='in_person', max_length=20)),
                ('location_name', models.CharField(blank=True, help_text='E.g., Library Room 301', max_length=255)),
                ('location_address', models.TextField(blank=True)),
                ('geom_point', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='Geographic location of the session', null=True, srid=4326)),
                ('meeting_link', models.URLField(blank=True, help_text='Zoom, Google Meet, etc.')),
                ('start_time', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('recurrence_pattern', models.CharField(choices=[('none', 'None'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='none', max_length=20)),
                ('recurrence_end_date', models.DateField(blank=True, help_text='When recurrence stops', null=True)),
                ('max_participants', models.PositiveIntegerField(blank=True, help_text='Maximum number of participants (null = unlimited)', null=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_sessions', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_sessions', to='learning.subject')),
            ],
            options={
                'db_table': 'study_sessions',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='SessionParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('attended', 'Attended'), ('no_show', 'No Show'), ('cancelled', 'Cancelled')], default='registered', max_length=20)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text="Participant's personal notes about the session")),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_participations', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='study_sessions.studysession')),
            ],
            options={
                'db_table': 'session_participants',
                'ordering': ['joined_at'],
            },
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['start_time'], name='study_sessi_start_t_e6707c_idx'),
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['status'], name='study_sessi_status_82ad92_idx'),
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['host'], name='study_sessi_host_id_1ab08f_idx'),
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['session_type'], name='study_sessi_session_405498_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionparticipant',
            index=models.Index(fields=['session', 'status'], name='session_par_session_299472_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionparticipant',
            index=models.Index(fields=['user'], name='session_par_user_id_d6ddcb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionparticipant',
            unique_together={('session', 'user')},
        ),
    ]
