# Generated by Django 5.2.7 on 2025-10-13 15:07

from django.db import migrations, models


def convert_old_states_to_accepted(apps, schema_editor):
    """Convert mutual and conversation states to accepted."""
    ConnectionRequest = apps.get_model('matching', 'ConnectionRequest')
    ConnectionRequest.objects.filter(
        state__in=['mutual', 'conversation']
    ).update(state='accepted')


def reverse_conversion(apps, schema_editor):
    """No reverse operation needed - keep as accepted."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        # First, migrate the data
        migrations.RunPython(
            convert_old_states_to_accepted,
            reverse_conversion
        ),
        # Then, remove the fields
        migrations.RemoveField(
            model_name='connectionrequest',
            name='conversation_started_at',
        ),
        migrations.RemoveField(
            model_name='connectionrequest',
            name='mutual_at',
        ),
        # Finally, update the field choices
        migrations.AlterField(
            model_name='connectionrequest',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('blocked', 'Blocked')], db_index=True, default='pending', help_text='Current state of the connection request', max_length=20),
        ),
    ]
