# Generated by Django 5.2.7 on 2025-10-11 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(db_index=True, help_text='Unique goal code', unique=True)),
                ('name', models.TextField(help_text='Goal name/description')),
                ('type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('milestone', 'Milestone')], help_text='Goal type (daily/weekly/monthly/etc.)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Goal',
                'verbose_name_plural': 'Goals',
                'db_table': 'goals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(db_index=True, help_text='Unique subject code', unique=True)),
                ('name_vi', models.TextField(help_text='Subject name in Vietnamese')),
                ('name_en', models.TextField(help_text='Subject name in English')),
                ('level', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], help_text='Subject difficulty level', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'db_table': 'subjects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_value', models.DecimalField(decimal_places=2, help_text='Target value for the goal', max_digits=10)),
                ('target_date', models.DateField(help_text='Target completion date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.ForeignKey(db_column='goal_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_goals', to='learning.goal')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Goal',
                'verbose_name_plural': 'User Goals',
                'db_table': 'user_goals',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'goal')},
            },
        ),
        migrations.CreateModel(
            name='UserSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], help_text="User's level in this subject", max_length=50)),
                ('intent', models.CharField(choices=[('learn', 'Learn'), ('teach', 'Teach'), ('both', 'Both')], help_text="User's intent (learn/teach/both)", max_length=50)),
                ('note', models.TextField(blank=True, default='', help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(db_column='subject_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_subjects', to='learning.subject')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_subjects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Subject',
                'verbose_name_plural': 'User Subjects',
                'db_table': 'user_subjects',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'subject')},
            },
        ),
    ]
