# Generated by Django 5.2.7 on 2025-10-11 04:46

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('geom_point', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='Geographic location of the city', null=True, srid=4326)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'db_table': 'cities',
                'indexes': [models.Index(fields=['name'], name='idx_cities_name')],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(blank=True, default='', max_length=100)),
                ('address', models.TextField()),
                ('geom_point', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='Geographic location of the school', null=True, srid=4326)),
                ('website', models.URLField(blank=True, max_length=500, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, db_column='city_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools', to='locations.city')),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
                'db_table': 'schools',
                'indexes': [models.Index(fields=['name'], name='idx_schools_name'), models.Index(fields=['city'], name='idx_schools_city')],
            },
        ),
    ]
