# Generated by Django 5.2.7 on 2025-10-11 08:46

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom_point', django.contrib.gis.db.models.fields.PointField(geography=True, help_text='Geographic location at the time of recording', srid=4326)),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Timestamp when the location was recorded')),
                ('accuracy', models.FloatField(blank=True, help_text='Location accuracy in meters (from GPS)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Location History',
                'verbose_name_plural': 'Location Histories',
                'db_table': 'location_history',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['user', '-recorded_at'], name='idx_location_user_time'), models.Index(fields=['recorded_at'], name='idx_location_recorded_at')],
            },
        ),
    ]
