# Generated by Django 5.2.7 on 2025-10-11 08:48
# Custom migration to add GIST index for geom_point field

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_locationhistory'),
    ]

    operations = [
        migrations.RunSQL(
            sql='CREATE INDEX idx_location_history_geom_point ON location_history USING GIST (geom_point);',
            reverse_sql='DROP INDEX IF EXISTS idx_location_history_geom_point;'
        ),
    ]
